### ISSUE TITLE
Remove NO_MODULE from Eigen test

### ISSUE THREAD

**Issue by tadeu** [conda-forge/cgal-cpp-feedstock#3]
This task is just to not forget to apply the suggestion from this comment: https://github.com/conda-forge/cgal-cpp-feedstock/pull/2#discussion_r271609355

**Comment by lrineau** [comment]
Since Eigen3 version 3.2, a config file `Eigen3Config.cmake` is shipped with Eigen3, and `FindEigen3.cmake` is no longer needed. It might be even harmful.

So `NO_MODULE` is perfectly fine with Eigen version 3.2 or later. This issue should be closed.
